name: Build and Publish to Docker Hub
on: push
jobs:
  Build-and-Publish-Docker-Hub:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: True
          tags: tontan2203/youtube-scraper:latest
  Build-and-Publish-Github-Packages:
    name: Build and Publish to Github Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build, Tag, Push
        uses: mattdavis0351/actions/docker-gpr@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: youtube-scraper
